### PR TITLE
make some CGameObject->Methods vtable struct callable

### PR DESCRIPTION
**Pull request by niv**
Amends the API structs to make vtables callable without explicit casting.

Also renames CNWSClient->vtable to Methods to match the naming scheme
of all others.

Only lightly tested and barely useful (but still useful). Specifically
missing is custom vtables for all object types that have them and more
CNWSObject-type methods are missing too; that's a problem left for
another day.

### CODE REVIEW

**Comment by virusman** [comment]
CNWSObjectMethods definition seems to be wrong: the updated methods are now at the bottom instead of being in the beginning of the struct.
Also, Methods is the older notation, I now tend to use <ClassName>_vtbl for vtable structs and vtable for the vtable pointer field. I was thinking about updating everything to conform to this notation with the next API update, but i'm open to suggestions. :)

**Comment by niv** [comment]
Pushed a fix for that awful git add -p mess i made. The rest we need to discuss ofc. :)

**Comment by jd28** [comment]
Looks like these have the NWC/NWS crossed:
```
    /* 0x54/84 */ void (*AsNWSPlaceable)(CGameObject*);
    /* 0x58/88 */ CNWSPlaceable* (*AsNWCPlaceable)(CGameObject*);
    /* 0x5C/92 */ void (*AsNWSAreaOfEffectObject)(CGameObject*);
    /* 0x60/96 */ CNWSAreaOfEffectObject* (*AsNWCAreaOfEffectObject)(CGameObject*);
```

**Comment by niv** [comment]
Thanks for catching that. :) But as discussed, this thing can go away anyways pending for the next api merge.

**Pull request closed without merging**
