### PR TITLE
core: add EVENT_CORE_MODULE_LOAD(ED|ING)

### PR DESCRIPTION
**Pull request by niv**
This embeds some in-function hooking. It's a bit messy but it shouldn't
conflict with any other plugins already messing with AdminLoadModule()

It also adds some static/inline helpers to do the actual hooking. We
might want to move them into a global include so every plugin can use them
but I couldn't be bothered to sort out the naming in this same PR.

Plz review thx xxxx

### CODE REVIEW

**Comment by virusman** [comment]
You can remove d_enable_write and use nx_hook_enable_write instead.

**Comment by niv** [comment]
Updated branch to use nx_hook_enable_write. Tested to work on my setup, but more eyes would always be good. Please review before merging.

**Comment by jd28** [comment]
Not to be a style stickler but these files use tabs for indentation.

**Comment by niv** [comment]
Updated to use spaces as per the style guide I wrote myself ..

This commit updates all affected files, seem to be some leftovers from previous commits there as well.

**Pull request merged**
