### PR TITLE
Updated some struct info.

### PR DESCRIPTION
**Pull request by ScholarMidnight**
Some struct corrections we needed to make when upgrading from the old API to the new API.

### CODE REVIEW

**Comment by jd28** [comment]
I'd suggest changing:

```c++
class CNWSScriptVarTable
{
    ...
    void* First;
    uint32_t Len;
};
```
to
```c++
class CNWSScriptVarTable
{
    ...
    CNWSScriptVar* List;
    uint32_t Len;
};
```

and 
```c++
struct CNWSScriptVar {
    /* 0x0/0 */ CExoString m_sName;
    /* 0x8/8 */ unsigned long m_nType;
    /* 0xC/12 */ unsigned long m_pValue;
};
to
```c++
struct CNWSScriptVar {
    /* 0x0/0 */ CExoString m_sName;
    /* 0x8/8 */ unsigned long m_nType;
    /* 0xC/12 */  union {
        nwobjid Object;
        int Int;
        float Float;
        CExoString* String;
        CScriptLocation* Location;
    } m_uValue;
};
```
in nwstructs.h.  That will complete the definition for CNWSScriptVarTable, obv. the names are up to you.

**Comment by ScholarMidnight** [comment]
Yeah, good call. I'll update the PR this evening.

**Comment by virusman** [comment]
Hey @ScholarMidnight, could you update this so I can merge? Thanks!

**Comment by virusman** [comment]
Merged. Thanks!

**Pull request closed without merging**
