### PR TITLE
plugins/areas: Add fix for creature missing minimap data.

### PR DESCRIPTION
**Pull request by jd28**
When an area is added or removed the current implementation does
not update the minimap data stored in player TURDs for logged out.
players.  This caused segfaults when a player entered an area created
since their last logout, since they have no minimap data for it.
This patch works around that fact by adding an additional NWNX function
"FIX" that must be called on every client that enters.

This function will remove all iterate the player's area list removing
all areas that are no longer in the module's area list.  Then iterate
the module's area list and add all newly added areas to the player's
area list.

### CODE REVIEW

**Comment by virusman** [comment]
Thanks!!
Is it possible to remove the NWScript call and hook somewhere directly?

**Comment by jd28** [comment]
Yea, CNWSPlayer::EatTURD would work well for that.  I'll make that change.  Might not be able to get to it until tomorrow tho.

**Comment by jd28** [comment]
Well EatTURD didn't seem to work, not sure why and didn't want to go too far down the rabbit hole on that.

So I tried looking at updating the TURDs again and noticed something weird.  I set up a module with a placeable.  When used it boots the player clicking it, then creates a delay command to create some areas after 3 seconds.  It attempts to add to logged in creatures then add to the TURD list (similarly to the RemoveArea function)... but pRealModule->TURDList.GetHeadPos() always seems to be NULL.  Do you have any idea why that would be?

**Comment by jd28** [comment]
Ok, I updated this to remove the NWScript thing.  I hooked CNWSCreature::SetAutoMapData and updated creatures there.

Compiled version used for testing: https://dl.dropboxusercontent.com/u/32687721/nwnx_areas.7z

**Comment by farhorizonnwn** [comment]
Running this on my server instead of my fix now & I can verify that it does work.

**Comment by virusman** [comment]
Thanks jd28!

**Pull request merged**
