### PR TITLE
api/CNWSPlayer: fix wrong fields & (nearly) complete class definition

### PR DESCRIPTION
**Pull request by niv**
CNWSPlayer actually had some wrongly-labelled fields.

I've fixed that (and grepped the tree briefly - couldn't find any users for them), and fleshed out the rest that was able to divine.

Note that this adds a class-scoped struct (it's not used anywhere else as far as I could tell).

Still wish we had a way to keep some proper documentation on all these fields/classes, there's lots of info just not getting into the repo.

### CODE REVIEW

**Comment by virusman** [comment]
Could you extract the struct to nwnstructs? I don't think we'll be able to handle things like class-scoped structs with API->IDA importer, at least in the beginning.

**Comment by niv** [comment]
Branch updates, please check!

**Comment by virusman** [comment]
CCharacterSheetGUIInfo and CNWSPlayerCharSheetGUI are the same. CNWSPlayer+0x60 is CNWSPlayerCharSheetGUI *

**Comment by virusman** [comment]
Thanks!

**Pull request merged**
